/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RastreioRouteImport } from './routes/rastreio'
import { Route as ProdutoRouteImport } from './routes/produto'
import { Route as PoliticaReembolsoRouteImport } from './routes/politica-reembolso'
import { Route as PoliticaPrivacidadeRouteImport } from './routes/politica-privacidade'
import { Route as PoliticaEnvioRouteImport } from './routes/politica-envio'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as UkRouteRouteImport } from './routes/uk/route'
import { Route as MxRouteRouteImport } from './routes/mx/route'
import { Route as DeRouteRouteImport } from './routes/de/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UkIndexRouteImport } from './routes/uk/index'
import { Route as MxIndexRouteImport } from './routes/mx/index'
import { Route as DeIndexRouteImport } from './routes/de/index'
import { Route as UkTrackingRouteImport } from './routes/uk/tracking'
import { Route as UkShippingRouteImport } from './routes/uk/shipping'
import { Route as UkRefundRouteImport } from './routes/uk/refund'
import { Route as UkProductRouteImport } from './routes/uk/product'
import { Route as UkPrivacyRouteImport } from './routes/uk/privacy'
import { Route as UkFaqRouteImport } from './routes/uk/faq'
import { Route as UkContactRouteImport } from './routes/uk/contact'
import { Route as UkCheckoutRouteImport } from './routes/uk/checkout'
import { Route as UkAboutRouteImport } from './routes/uk/about'
import { Route as MxReembolsosRouteImport } from './routes/mx/reembolsos'
import { Route as MxRastreoRouteImport } from './routes/mx/rastreo'
import { Route as MxProductoRouteImport } from './routes/mx/producto'
import { Route as MxPrivacidadRouteImport } from './routes/mx/privacidad'
import { Route as MxNosotrosRouteImport } from './routes/mx/nosotros'
import { Route as MxFaqRouteImport } from './routes/mx/faq'
import { Route as MxEnviosRouteImport } from './routes/mx/envios'
import { Route as MxContactoRouteImport } from './routes/mx/contacto'
import { Route as MxCheckoutRouteImport } from './routes/mx/checkout'
import { Route as DeVersandRouteImport } from './routes/de/versand'
import { Route as DeUeberUnsRouteImport } from './routes/de/ueber-uns'
import { Route as DeSendungsverfolgungRouteImport } from './routes/de/sendungsverfolgung'
import { Route as DeRueckerstattungRouteImport } from './routes/de/rueckerstattung'
import { Route as DeProduktRouteImport } from './routes/de/produkt'
import { Route as DeKontaktRouteImport } from './routes/de/kontakt'
import { Route as DeFaqRouteImport } from './routes/de/faq'
import { Route as DeDatenschutzRouteImport } from './routes/de/datenschutz'
import { Route as DeCheckoutRouteImport } from './routes/de/checkout'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreioRoute = RastreioRouteImport.update({
  id: '/rastreio',
  path: '/rastreio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoRoute = ProdutoRouteImport.update({
  id: '/produto',
  path: '/produto',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaReembolsoRoute = PoliticaReembolsoRouteImport.update({
  id: '/politica-reembolso',
  path: '/politica-reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadeRoute = PoliticaPrivacidadeRouteImport.update({
  id: '/politica-privacidade',
  path: '/politica-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaEnvioRoute = PoliticaEnvioRouteImport.update({
  id: '/politica-envio',
  path: '/politica-envio',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UkRouteRoute = UkRouteRouteImport.update({
  id: '/uk',
  path: '/uk',
  getParentRoute: () => rootRouteImport,
} as any)
const MxRouteRoute = MxRouteRouteImport.update({
  id: '/mx',
  path: '/mx',
  getParentRoute: () => rootRouteImport,
} as any)
const DeRouteRoute = DeRouteRouteImport.update({
  id: '/de',
  path: '/de',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UkIndexRoute = UkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UkRouteRoute,
} as any)
const MxIndexRoute = MxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MxRouteRoute,
} as any)
const DeIndexRoute = DeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeRouteRoute,
} as any)
const UkTrackingRoute = UkTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => UkRouteRoute,
} as any)
const UkShippingRoute = UkShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => UkRouteRoute,
} as any)
const UkRefundRoute = UkRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => UkRouteRoute,
} as any)
const UkProductRoute = UkProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => UkRouteRoute,
} as any)
const UkPrivacyRoute = UkPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => UkRouteRoute,
} as any)
const UkFaqRoute = UkFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => UkRouteRoute,
} as any)
const UkContactRoute = UkContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => UkRouteRoute,
} as any)
const UkCheckoutRoute = UkCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => UkRouteRoute,
} as any)
const UkAboutRoute = UkAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => UkRouteRoute,
} as any)
const MxReembolsosRoute = MxReembolsosRouteImport.update({
  id: '/reembolsos',
  path: '/reembolsos',
  getParentRoute: () => MxRouteRoute,
} as any)
const MxRastreoRoute = MxRastreoRouteImport.update({
  id: '/rastreo',
  path: '/rastreo',
  getParentRoute: () => MxRouteRoute,
} as any)
const MxProductoRoute = MxProductoRouteImport.update({
  id: '/producto',
  path: '/producto',
  getParentRoute: () => MxRouteRoute,
} as any)
const MxPrivacidadRoute = MxPrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => MxRouteRoute,
} as any)
const MxNosotrosRoute = MxNosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => MxRouteRoute,
} as any)
const MxFaqRoute = MxFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => MxRouteRoute,
} as any)
const MxEnviosRoute = MxEnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => MxRouteRoute,
} as any)
const MxContactoRoute = MxContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => MxRouteRoute,
} as any)
const MxCheckoutRoute = MxCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => MxRouteRoute,
} as any)
const DeVersandRoute = DeVersandRouteImport.update({
  id: '/versand',
  path: '/versand',
  getParentRoute: () => DeRouteRoute,
} as any)
const DeUeberUnsRoute = DeUeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => DeRouteRoute,
} as any)
const DeSendungsverfolgungRoute = DeSendungsverfolgungRouteImport.update({
  id: '/sendungsverfolgung',
  path: '/sendungsverfolgung',
  getParentRoute: () => DeRouteRoute,
} as any)
const DeRueckerstattungRoute = DeRueckerstattungRouteImport.update({
  id: '/rueckerstattung',
  path: '/rueckerstattung',
  getParentRoute: () => DeRouteRoute,
} as any)
const DeProduktRoute = DeProduktRouteImport.update({
  id: '/produkt',
  path: '/produkt',
  getParentRoute: () => DeRouteRoute,
} as any)
const DeKontaktRoute = DeKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => DeRouteRoute,
} as any)
const DeFaqRoute = DeFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DeRouteRoute,
} as any)
const DeDatenschutzRoute = DeDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => DeRouteRoute,
} as any)
const DeCheckoutRoute = DeCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => DeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/de': typeof DeRouteRouteWithChildren
  '/mx': typeof MxRouteRouteWithChildren
  '/uk': typeof UkRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/politica-envio': typeof PoliticaEnvioRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/politica-reembolso': typeof PoliticaReembolsoRoute
  '/produto': typeof ProdutoRoute
  '/rastreio': typeof RastreioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/de/checkout': typeof DeCheckoutRoute
  '/de/datenschutz': typeof DeDatenschutzRoute
  '/de/faq': typeof DeFaqRoute
  '/de/kontakt': typeof DeKontaktRoute
  '/de/produkt': typeof DeProduktRoute
  '/de/rueckerstattung': typeof DeRueckerstattungRoute
  '/de/sendungsverfolgung': typeof DeSendungsverfolgungRoute
  '/de/ueber-uns': typeof DeUeberUnsRoute
  '/de/versand': typeof DeVersandRoute
  '/mx/checkout': typeof MxCheckoutRoute
  '/mx/contacto': typeof MxContactoRoute
  '/mx/envios': typeof MxEnviosRoute
  '/mx/faq': typeof MxFaqRoute
  '/mx/nosotros': typeof MxNosotrosRoute
  '/mx/privacidad': typeof MxPrivacidadRoute
  '/mx/producto': typeof MxProductoRoute
  '/mx/rastreo': typeof MxRastreoRoute
  '/mx/reembolsos': typeof MxReembolsosRoute
  '/uk/about': typeof UkAboutRoute
  '/uk/checkout': typeof UkCheckoutRoute
  '/uk/contact': typeof UkContactRoute
  '/uk/faq': typeof UkFaqRoute
  '/uk/privacy': typeof UkPrivacyRoute
  '/uk/product': typeof UkProductRoute
  '/uk/refund': typeof UkRefundRoute
  '/uk/shipping': typeof UkShippingRoute
  '/uk/tracking': typeof UkTrackingRoute
  '/de/': typeof DeIndexRoute
  '/mx/': typeof MxIndexRoute
  '/uk/': typeof UkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/politica-envio': typeof PoliticaEnvioRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/politica-reembolso': typeof PoliticaReembolsoRoute
  '/produto': typeof ProdutoRoute
  '/rastreio': typeof RastreioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/de/checkout': typeof DeCheckoutRoute
  '/de/datenschutz': typeof DeDatenschutzRoute
  '/de/faq': typeof DeFaqRoute
  '/de/kontakt': typeof DeKontaktRoute
  '/de/produkt': typeof DeProduktRoute
  '/de/rueckerstattung': typeof DeRueckerstattungRoute
  '/de/sendungsverfolgung': typeof DeSendungsverfolgungRoute
  '/de/ueber-uns': typeof DeUeberUnsRoute
  '/de/versand': typeof DeVersandRoute
  '/mx/checkout': typeof MxCheckoutRoute
  '/mx/contacto': typeof MxContactoRoute
  '/mx/envios': typeof MxEnviosRoute
  '/mx/faq': typeof MxFaqRoute
  '/mx/nosotros': typeof MxNosotrosRoute
  '/mx/privacidad': typeof MxPrivacidadRoute
  '/mx/producto': typeof MxProductoRoute
  '/mx/rastreo': typeof MxRastreoRoute
  '/mx/reembolsos': typeof MxReembolsosRoute
  '/uk/about': typeof UkAboutRoute
  '/uk/checkout': typeof UkCheckoutRoute
  '/uk/contact': typeof UkContactRoute
  '/uk/faq': typeof UkFaqRoute
  '/uk/privacy': typeof UkPrivacyRoute
  '/uk/product': typeof UkProductRoute
  '/uk/refund': typeof UkRefundRoute
  '/uk/shipping': typeof UkShippingRoute
  '/uk/tracking': typeof UkTrackingRoute
  '/de': typeof DeIndexRoute
  '/mx': typeof MxIndexRoute
  '/uk': typeof UkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/de': typeof DeRouteRouteWithChildren
  '/mx': typeof MxRouteRouteWithChildren
  '/uk': typeof UkRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/politica-envio': typeof PoliticaEnvioRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/politica-reembolso': typeof PoliticaReembolsoRoute
  '/produto': typeof ProdutoRoute
  '/rastreio': typeof RastreioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/de/checkout': typeof DeCheckoutRoute
  '/de/datenschutz': typeof DeDatenschutzRoute
  '/de/faq': typeof DeFaqRoute
  '/de/kontakt': typeof DeKontaktRoute
  '/de/produkt': typeof DeProduktRoute
  '/de/rueckerstattung': typeof DeRueckerstattungRoute
  '/de/sendungsverfolgung': typeof DeSendungsverfolgungRoute
  '/de/ueber-uns': typeof DeUeberUnsRoute
  '/de/versand': typeof DeVersandRoute
  '/mx/checkout': typeof MxCheckoutRoute
  '/mx/contacto': typeof MxContactoRoute
  '/mx/envios': typeof MxEnviosRoute
  '/mx/faq': typeof MxFaqRoute
  '/mx/nosotros': typeof MxNosotrosRoute
  '/mx/privacidad': typeof MxPrivacidadRoute
  '/mx/producto': typeof MxProductoRoute
  '/mx/rastreo': typeof MxRastreoRoute
  '/mx/reembolsos': typeof MxReembolsosRoute
  '/uk/about': typeof UkAboutRoute
  '/uk/checkout': typeof UkCheckoutRoute
  '/uk/contact': typeof UkContactRoute
  '/uk/faq': typeof UkFaqRoute
  '/uk/privacy': typeof UkPrivacyRoute
  '/uk/product': typeof UkProductRoute
  '/uk/refund': typeof UkRefundRoute
  '/uk/shipping': typeof UkShippingRoute
  '/uk/tracking': typeof UkTrackingRoute
  '/de/': typeof DeIndexRoute
  '/mx/': typeof MxIndexRoute
  '/uk/': typeof UkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/de'
    | '/mx'
    | '/uk'
    | '/admin'
    | '/checkout'
    | '/contato'
    | '/faq'
    | '/politica-envio'
    | '/politica-privacidade'
    | '/politica-reembolso'
    | '/produto'
    | '/rastreio'
    | '/sitemap.xml'
    | '/sobre'
    | '/de/checkout'
    | '/de/datenschutz'
    | '/de/faq'
    | '/de/kontakt'
    | '/de/produkt'
    | '/de/rueckerstattung'
    | '/de/sendungsverfolgung'
    | '/de/ueber-uns'
    | '/de/versand'
    | '/mx/checkout'
    | '/mx/contacto'
    | '/mx/envios'
    | '/mx/faq'
    | '/mx/nosotros'
    | '/mx/privacidad'
    | '/mx/producto'
    | '/mx/rastreo'
    | '/mx/reembolsos'
    | '/uk/about'
    | '/uk/checkout'
    | '/uk/contact'
    | '/uk/faq'
    | '/uk/privacy'
    | '/uk/product'
    | '/uk/refund'
    | '/uk/shipping'
    | '/uk/tracking'
    | '/de/'
    | '/mx/'
    | '/uk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/contato'
    | '/faq'
    | '/politica-envio'
    | '/politica-privacidade'
    | '/politica-reembolso'
    | '/produto'
    | '/rastreio'
    | '/sitemap.xml'
    | '/sobre'
    | '/de/checkout'
    | '/de/datenschutz'
    | '/de/faq'
    | '/de/kontakt'
    | '/de/produkt'
    | '/de/rueckerstattung'
    | '/de/sendungsverfolgung'
    | '/de/ueber-uns'
    | '/de/versand'
    | '/mx/checkout'
    | '/mx/contacto'
    | '/mx/envios'
    | '/mx/faq'
    | '/mx/nosotros'
    | '/mx/privacidad'
    | '/mx/producto'
    | '/mx/rastreo'
    | '/mx/reembolsos'
    | '/uk/about'
    | '/uk/checkout'
    | '/uk/contact'
    | '/uk/faq'
    | '/uk/privacy'
    | '/uk/product'
    | '/uk/refund'
    | '/uk/shipping'
    | '/uk/tracking'
    | '/de'
    | '/mx'
    | '/uk'
  id:
    | '__root__'
    | '/'
    | '/de'
    | '/mx'
    | '/uk'
    | '/admin'
    | '/checkout'
    | '/contato'
    | '/faq'
    | '/politica-envio'
    | '/politica-privacidade'
    | '/politica-reembolso'
    | '/produto'
    | '/rastreio'
    | '/sitemap.xml'
    | '/sobre'
    | '/de/checkout'
    | '/de/datenschutz'
    | '/de/faq'
    | '/de/kontakt'
    | '/de/produkt'
    | '/de/rueckerstattung'
    | '/de/sendungsverfolgung'
    | '/de/ueber-uns'
    | '/de/versand'
    | '/mx/checkout'
    | '/mx/contacto'
    | '/mx/envios'
    | '/mx/faq'
    | '/mx/nosotros'
    | '/mx/privacidad'
    | '/mx/producto'
    | '/mx/rastreo'
    | '/mx/reembolsos'
    | '/uk/about'
    | '/uk/checkout'
    | '/uk/contact'
    | '/uk/faq'
    | '/uk/privacy'
    | '/uk/product'
    | '/uk/refund'
    | '/uk/shipping'
    | '/uk/tracking'
    | '/de/'
    | '/mx/'
    | '/uk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeRouteRoute: typeof DeRouteRouteWithChildren
  MxRouteRoute: typeof MxRouteRouteWithChildren
  UkRouteRoute: typeof UkRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  PoliticaEnvioRoute: typeof PoliticaEnvioRoute
  PoliticaPrivacidadeRoute: typeof PoliticaPrivacidadeRoute
  PoliticaReembolsoRoute: typeof PoliticaReembolsoRoute
  ProdutoRoute: typeof ProdutoRoute
  RastreioRoute: typeof RastreioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreio': {
      id: '/rastreio'
      path: '/rastreio'
      fullPath: '/rastreio'
      preLoaderRoute: typeof RastreioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto': {
      id: '/produto'
      path: '/produto'
      fullPath: '/produto'
      preLoaderRoute: typeof ProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-reembolso': {
      id: '/politica-reembolso'
      path: '/politica-reembolso'
      fullPath: '/politica-reembolso'
      preLoaderRoute: typeof PoliticaReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidade': {
      id: '/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof PoliticaPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-envio': {
      id: '/politica-envio'
      path: '/politica-envio'
      fullPath: '/politica-envio'
      preLoaderRoute: typeof PoliticaEnvioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uk': {
      id: '/uk'
      path: '/uk'
      fullPath: '/uk'
      preLoaderRoute: typeof UkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mx': {
      id: '/mx'
      path: '/mx'
      fullPath: '/mx'
      preLoaderRoute: typeof MxRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de': {
      id: '/de'
      path: '/de'
      fullPath: '/de'
      preLoaderRoute: typeof DeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uk/': {
      id: '/uk/'
      path: '/'
      fullPath: '/uk/'
      preLoaderRoute: typeof UkIndexRouteImport
      parentRoute: typeof UkRouteRoute
    }
    '/mx/': {
      id: '/mx/'
      path: '/'
      fullPath: '/mx/'
      preLoaderRoute: typeof MxIndexRouteImport
      parentRoute: typeof MxRouteRoute
    }
    '/de/': {
      id: '/de/'
      path: '/'
      fullPath: '/de/'
      preLoaderRoute: typeof DeIndexRouteImport
      parentRoute: typeof DeRouteRoute
    }
    '/uk/tracking': {
      id: '/uk/tracking'
      path: '/tracking'
      fullPath: '/uk/tracking'
      preLoaderRoute: typeof UkTrackingRouteImport
      parentRoute: typeof UkRouteRoute
    }
    '/uk/shipping': {
      id: '/uk/shipping'
      path: '/shipping'
      fullPath: '/uk/shipping'
      preLoaderRoute: typeof UkShippingRouteImport
      parentRoute: typeof UkRouteRoute
    }
    '/uk/refund': {
      id: '/uk/refund'
      path: '/refund'
      fullPath: '/uk/refund'
      preLoaderRoute: typeof UkRefundRouteImport
      parentRoute: typeof UkRouteRoute
    }
    '/uk/product': {
      id: '/uk/product'
      path: '/product'
      fullPath: '/uk/product'
      preLoaderRoute: typeof UkProductRouteImport
      parentRoute: typeof UkRouteRoute
    }
    '/uk/privacy': {
      id: '/uk/privacy'
      path: '/privacy'
      fullPath: '/uk/privacy'
      preLoaderRoute: typeof UkPrivacyRouteImport
      parentRoute: typeof UkRouteRoute
    }
    '/uk/faq': {
      id: '/uk/faq'
      path: '/faq'
      fullPath: '/uk/faq'
      preLoaderRoute: typeof UkFaqRouteImport
      parentRoute: typeof UkRouteRoute
    }
    '/uk/contact': {
      id: '/uk/contact'
      path: '/contact'
      fullPath: '/uk/contact'
      preLoaderRoute: typeof UkContactRouteImport
      parentRoute: typeof UkRouteRoute
    }
    '/uk/checkout': {
      id: '/uk/checkout'
      path: '/checkout'
      fullPath: '/uk/checkout'
      preLoaderRoute: typeof UkCheckoutRouteImport
      parentRoute: typeof UkRouteRoute
    }
    '/uk/about': {
      id: '/uk/about'
      path: '/about'
      fullPath: '/uk/about'
      preLoaderRoute: typeof UkAboutRouteImport
      parentRoute: typeof UkRouteRoute
    }
    '/mx/reembolsos': {
      id: '/mx/reembolsos'
      path: '/reembolsos'
      fullPath: '/mx/reembolsos'
      preLoaderRoute: typeof MxReembolsosRouteImport
      parentRoute: typeof MxRouteRoute
    }
    '/mx/rastreo': {
      id: '/mx/rastreo'
      path: '/rastreo'
      fullPath: '/mx/rastreo'
      preLoaderRoute: typeof MxRastreoRouteImport
      parentRoute: typeof MxRouteRoute
    }
    '/mx/producto': {
      id: '/mx/producto'
      path: '/producto'
      fullPath: '/mx/producto'
      preLoaderRoute: typeof MxProductoRouteImport
      parentRoute: typeof MxRouteRoute
    }
    '/mx/privacidad': {
      id: '/mx/privacidad'
      path: '/privacidad'
      fullPath: '/mx/privacidad'
      preLoaderRoute: typeof MxPrivacidadRouteImport
      parentRoute: typeof MxRouteRoute
    }
    '/mx/nosotros': {
      id: '/mx/nosotros'
      path: '/nosotros'
      fullPath: '/mx/nosotros'
      preLoaderRoute: typeof MxNosotrosRouteImport
      parentRoute: typeof MxRouteRoute
    }
    '/mx/faq': {
      id: '/mx/faq'
      path: '/faq'
      fullPath: '/mx/faq'
      preLoaderRoute: typeof MxFaqRouteImport
      parentRoute: typeof MxRouteRoute
    }
    '/mx/envios': {
      id: '/mx/envios'
      path: '/envios'
      fullPath: '/mx/envios'
      preLoaderRoute: typeof MxEnviosRouteImport
      parentRoute: typeof MxRouteRoute
    }
    '/mx/contacto': {
      id: '/mx/contacto'
      path: '/contacto'
      fullPath: '/mx/contacto'
      preLoaderRoute: typeof MxContactoRouteImport
      parentRoute: typeof MxRouteRoute
    }
    '/mx/checkout': {
      id: '/mx/checkout'
      path: '/checkout'
      fullPath: '/mx/checkout'
      preLoaderRoute: typeof MxCheckoutRouteImport
      parentRoute: typeof MxRouteRoute
    }
    '/de/versand': {
      id: '/de/versand'
      path: '/versand'
      fullPath: '/de/versand'
      preLoaderRoute: typeof DeVersandRouteImport
      parentRoute: typeof DeRouteRoute
    }
    '/de/ueber-uns': {
      id: '/de/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/de/ueber-uns'
      preLoaderRoute: typeof DeUeberUnsRouteImport
      parentRoute: typeof DeRouteRoute
    }
    '/de/sendungsverfolgung': {
      id: '/de/sendungsverfolgung'
      path: '/sendungsverfolgung'
      fullPath: '/de/sendungsverfolgung'
      preLoaderRoute: typeof DeSendungsverfolgungRouteImport
      parentRoute: typeof DeRouteRoute
    }
    '/de/rueckerstattung': {
      id: '/de/rueckerstattung'
      path: '/rueckerstattung'
      fullPath: '/de/rueckerstattung'
      preLoaderRoute: typeof DeRueckerstattungRouteImport
      parentRoute: typeof DeRouteRoute
    }
    '/de/produkt': {
      id: '/de/produkt'
      path: '/produkt'
      fullPath: '/de/produkt'
      preLoaderRoute: typeof DeProduktRouteImport
      parentRoute: typeof DeRouteRoute
    }
    '/de/kontakt': {
      id: '/de/kontakt'
      path: '/kontakt'
      fullPath: '/de/kontakt'
      preLoaderRoute: typeof DeKontaktRouteImport
      parentRoute: typeof DeRouteRoute
    }
    '/de/faq': {
      id: '/de/faq'
      path: '/faq'
      fullPath: '/de/faq'
      preLoaderRoute: typeof DeFaqRouteImport
      parentRoute: typeof DeRouteRoute
    }
    '/de/datenschutz': {
      id: '/de/datenschutz'
      path: '/datenschutz'
      fullPath: '/de/datenschutz'
      preLoaderRoute: typeof DeDatenschutzRouteImport
      parentRoute: typeof DeRouteRoute
    }
    '/de/checkout': {
      id: '/de/checkout'
      path: '/checkout'
      fullPath: '/de/checkout'
      preLoaderRoute: typeof DeCheckoutRouteImport
      parentRoute: typeof DeRouteRoute
    }
  }
}

interface DeRouteRouteChildren {
  DeCheckoutRoute: typeof DeCheckoutRoute
  DeDatenschutzRoute: typeof DeDatenschutzRoute
  DeFaqRoute: typeof DeFaqRoute
  DeKontaktRoute: typeof DeKontaktRoute
  DeProduktRoute: typeof DeProduktRoute
  DeRueckerstattungRoute: typeof DeRueckerstattungRoute
  DeSendungsverfolgungRoute: typeof DeSendungsverfolgungRoute
  DeUeberUnsRoute: typeof DeUeberUnsRoute
  DeVersandRoute: typeof DeVersandRoute
  DeIndexRoute: typeof DeIndexRoute
}

const DeRouteRouteChildren: DeRouteRouteChildren = {
  DeCheckoutRoute: DeCheckoutRoute,
  DeDatenschutzRoute: DeDatenschutzRoute,
  DeFaqRoute: DeFaqRoute,
  DeKontaktRoute: DeKontaktRoute,
  DeProduktRoute: DeProduktRoute,
  DeRueckerstattungRoute: DeRueckerstattungRoute,
  DeSendungsverfolgungRoute: DeSendungsverfolgungRoute,
  DeUeberUnsRoute: DeUeberUnsRoute,
  DeVersandRoute: DeVersandRoute,
  DeIndexRoute: DeIndexRoute,
}

const DeRouteRouteWithChildren =
  DeRouteRoute._addFileChildren(DeRouteRouteChildren)

interface MxRouteRouteChildren {
  MxCheckoutRoute: typeof MxCheckoutRoute
  MxContactoRoute: typeof MxContactoRoute
  MxEnviosRoute: typeof MxEnviosRoute
  MxFaqRoute: typeof MxFaqRoute
  MxNosotrosRoute: typeof MxNosotrosRoute
  MxPrivacidadRoute: typeof MxPrivacidadRoute
  MxProductoRoute: typeof MxProductoRoute
  MxRastreoRoute: typeof MxRastreoRoute
  MxReembolsosRoute: typeof MxReembolsosRoute
  MxIndexRoute: typeof MxIndexRoute
}

const MxRouteRouteChildren: MxRouteRouteChildren = {
  MxCheckoutRoute: MxCheckoutRoute,
  MxContactoRoute: MxContactoRoute,
  MxEnviosRoute: MxEnviosRoute,
  MxFaqRoute: MxFaqRoute,
  MxNosotrosRoute: MxNosotrosRoute,
  MxPrivacidadRoute: MxPrivacidadRoute,
  MxProductoRoute: MxProductoRoute,
  MxRastreoRoute: MxRastreoRoute,
  MxReembolsosRoute: MxReembolsosRoute,
  MxIndexRoute: MxIndexRoute,
}

const MxRouteRouteWithChildren =
  MxRouteRoute._addFileChildren(MxRouteRouteChildren)

interface UkRouteRouteChildren {
  UkAboutRoute: typeof UkAboutRoute
  UkCheckoutRoute: typeof UkCheckoutRoute
  UkContactRoute: typeof UkContactRoute
  UkFaqRoute: typeof UkFaqRoute
  UkPrivacyRoute: typeof UkPrivacyRoute
  UkProductRoute: typeof UkProductRoute
  UkRefundRoute: typeof UkRefundRoute
  UkShippingRoute: typeof UkShippingRoute
  UkTrackingRoute: typeof UkTrackingRoute
  UkIndexRoute: typeof UkIndexRoute
}

const UkRouteRouteChildren: UkRouteRouteChildren = {
  UkAboutRoute: UkAboutRoute,
  UkCheckoutRoute: UkCheckoutRoute,
  UkContactRoute: UkContactRoute,
  UkFaqRoute: UkFaqRoute,
  UkPrivacyRoute: UkPrivacyRoute,
  UkProductRoute: UkProductRoute,
  UkRefundRoute: UkRefundRoute,
  UkShippingRoute: UkShippingRoute,
  UkTrackingRoute: UkTrackingRoute,
  UkIndexRoute: UkIndexRoute,
}

const UkRouteRouteWithChildren =
  UkRouteRoute._addFileChildren(UkRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeRouteRoute: DeRouteRouteWithChildren,
  MxRouteRoute: MxRouteRouteWithChildren,
  UkRouteRoute: UkRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  PoliticaEnvioRoute: PoliticaEnvioRoute,
  PoliticaPrivacidadeRoute: PoliticaPrivacidadeRoute,
  PoliticaReembolsoRoute: PoliticaReembolsoRoute,
  ProdutoRoute: ProdutoRoute,
  RastreioRoute: RastreioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
